### ISSUE TITLE
Dzielenie przez 0

### ISSUE THREAD

**Issue by kkoziol** [pawelbabiuch/sternik-zadania#1]
Do zad 10 napisz test uwzgledniajacy mozliwosc wystapienia dzielenia przez zero.
czyli podaj odpowiednie dane wejscowe i napraw ewentualnie problem.

**Comment by pawelbabiuch** [comment]
Poprawiałem zadanie wraz z mailem, którego dostałem. Tak więc... jest tu tylko drobna poprawka. Ticketa zauważyłem trochę za późno, a już nie chciałem cofać specjalnie zmian. Kolejny ticket prawdopodobnie będzie podobnie rozwiązany.

**Comment by kkoziol** [comment]
ok

W dniu 19 lutego 2018 12:27 użytkownik pawelbabiuch <
notifications@github.com> napisał:

**Comment by kkoziol** [comment]
A dlaczego wolałeś zwracać coś zamiast rzucać wyjątkiem?

**Comment by kkoziol** [comment]
Ja tylko pytałem dlaczego takie rozwiazanie wybrales :)
A co do poprawki, to test ok.
A w kodzie, bardziej mi chodzilo by samemu rzucic wyjatkiem, albo go zadeklarowac.
Ale poprzednie tez było ok.
Dobra zamykamy.
