### ISSUE TITLE
Poprawka "builda"

### ISSUE THREAD

**Issue by kkoziol** [pawelbabiuch/sternik-zadania#4]
W ostatnim buildzie Travis pokazuje error:

> 
>[ERROR] COMPILATION ERROR : 
>[INFO] -------------------------------------------------------------
>[ERROR] /home/travis/build/pawelbabiuch/sternik-zadania/src/main/java/pl/sternik/pb/zadania/zad35/Article.java:[1,1] illegal character: '\ufeff'
>[ERROR] /home/travis/build/pawelbabiuch/sternik-zadania/src/main/java/pl/sternik/pb/zadania/zad35/Article.java:[1,10] class, interface, or enum expected
>

No słabo projekt sie nie kompiluje? 
:-1:

**Comment by pawelbabiuch** [comment]
Z praktyki wiem, że dodawanie zbyt długich komentarzy do commitów nie jest mile widziane, więc postanowiłem wyjaśnienie napisać w oddzielnym komentarzu. Sam pik nie wymagał żadnej widocznej zmiany. Problem był z kodowaniem (utf-8), które było wcześniej - krzyczało o błąd. Zmieniłem na ISO 8859-1 i błąd ustąpił. Nie wiem dlaczego tak się stało, skoro każdy plik tworzę w ten sam sposób.

**Comment by kkoziol** [comment]
Z praktyki wiem, ze jedni lubia długie a inni nie, komentarze ;)
O golnie trzeba dostosowac do sytuacji ;) 
Mi tam wszystko jedno, aby był numer ticketa w message.

Co do kodowania. To mozliwe ze wczesniej było inne, potem zmieniłeś na utf, ale zmiana w IDE, nie konwertuje raczej automatem, pliku, wiec caly czas znak był w poprzednim kodowaniu.
